# Form implementation generated from reading ui file 'Project2GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 620)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Project_Title = QtWidgets.QLabel(parent=self.centralwidget)
        self.Project_Title.setGeometry(QtCore.QRect(90, 60, 101, 16))
        self.Project_Title.setObjectName("Project_Title")
        self.attempt_counter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.attempt_counter_label.setGeometry(QtCore.QRect(90, 80, 101, 41))
        self.attempt_counter_label.setAutoFillBackground(True)
        self.attempt_counter_label.setObjectName("attempt_counter_label")
        self.quiz_submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quiz_submit_button.setGeometry(QtCore.QRect(160, 250, 113, 32))
        self.quiz_submit_button.setObjectName("quiz_submit_button")
        self.hint_answer_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.hint_answer_label.setGeometry(QtCore.QRect(40, 130, 221, 16))
        self.hint_answer_label.setObjectName("hint_answer_label")
        self.q1_hint_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.q1_hint_label.setGeometry(QtCore.QRect(40, 160, 111, 21))
        self.q1_hint_label.setObjectName("q1_hint_label")
        self.q1_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.q1_lineEdit.setGeometry(QtCore.QRect(160, 160, 113, 21))
        self.q1_lineEdit.setObjectName("q1_lineEdit")
        self.q2_hint_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.q2_hint_label.setGeometry(QtCore.QRect(40, 190, 111, 21))
        self.q2_hint_label.setObjectName("q2_hint_label")
        self.q2_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.q2_lineEdit.setGeometry(QtCore.QRect(160, 190, 113, 21))
        self.q2_lineEdit.setObjectName("q2_lineEdit")
        self.q3_hint_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.q3_hint_label.setGeometry(QtCore.QRect(40, 220, 111, 21))
        self.q3_hint_label.setObjectName("q3_hint_label")
        self.q3_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.q3_lineEdit.setGeometry(QtCore.QRect(160, 220, 113, 21))
        self.q3_lineEdit.setObjectName("q3_lineEdit")
        self.home_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.home_frame.setGeometry(QtCore.QRect(20, 320, 281, 231))
        self.home_frame.setAutoFillBackground(True)
        self.home_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.home_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.home_frame.setObjectName("home_frame")
        self.to_quiz_button_home_frame = QtWidgets.QPushButton(parent=self.home_frame)
        self.to_quiz_button_home_frame.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.to_quiz_button_home_frame.setObjectName("to_quiz_button_home_frame")
        self.win_lose_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.win_lose_frame.setGeometry(QtCore.QRect(320, 60, 281, 231))
        self.win_lose_frame.setAutoFillBackground(True)
        self.win_lose_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.win_lose_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.win_lose_frame.setObjectName("win_lose_frame")
        self.win_lose_label = QtWidgets.QLabel(parent=self.win_lose_frame)
        self.win_lose_label.setGeometry(QtCore.QRect(70, 30, 121, 71))
        self.win_lose_label.setObjectName("win_lose_label")
        self.to_home_button_win_lose_frame = QtWidgets.QPushButton(parent=self.win_lose_frame)
        self.to_home_button_win_lose_frame.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.to_home_button_win_lose_frame.setObjectName("to_home_button_win_lose_frame")
        self.to_home_button_quiz_frame = QtWidgets.QPushButton(parent=self.centralwidget)
        self.to_home_button_quiz_frame.setGeometry(QtCore.QRect(20, 250, 113, 32))
        self.to_home_button_quiz_frame.setObjectName("to_home_button_quiz_frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Project_Title.setText(_translate("MainWindow", "Superhero Quiz"))
        self.attempt_counter_label.setText(_translate("MainWindow", "0/3 attempts"))
        self.quiz_submit_button.setText(_translate("MainWindow", "Submit"))
        self.hint_answer_label.setText(_translate("MainWindow", "Hints                         Answer"))
        self.q1_hint_label.setText(_translate("MainWindow", "TextLabel"))
        self.q2_hint_label.setText(_translate("MainWindow", "TextLabel"))
        self.q3_hint_label.setText(_translate("MainWindow", "TextLabel"))
        self.to_quiz_button_home_frame.setText(_translate("MainWindow", "Start Quiz"))
        self.win_lose_label.setText(_translate("MainWindow", "W/L"))
        self.to_home_button_win_lose_frame.setText(_translate("MainWindow", "Home"))
        self.to_home_button_quiz_frame.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
